Bump activemodel and actionpack (#181)
Bumps [activemodel](https://github.com/rails/rails) and
[actionpack](https://github.com/rails/rails). These dependencies needed
to be updated together.
Updates `activemodel` from 7.0.6 to 7.0.7
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activemodel's
releases</a>.</em></p>
<blockquote>
<h2>7.0.7</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>Cache::NullStore</code> with local caching for repeated
reads.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix <code>to_s</code> with no arguments not respecting custom
<code>:default</code> formats</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising
<code>NoMethodError: undefined method `end_with?' for
nil:NilClass</code>.</p>
<p><em>James Robinson</em></p>
</li>
<li>
<p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p>
<p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan
Hefner</em></p>
</li>
<li>
<p>Improve error message when EventedFileUpdateChecker is used without a
compatible version of the Listen gem</p>
<p><em>Hartley McGuire</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Error.full_message now strips &quot;:base&quot; from the message.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Add a load hook for <code>ActiveModel::Model</code> (named
<code>active_model</code>) to match the load hook for
<code>ActiveRecord::Base</code> and allow for overriding aspects of the
<code>ActiveModel::Model</code> class.</p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Restores functionality to the missing method when using enums and
fixes.</p>
<p><em>paulreece</em></p>
</li>
<li>
<p>Fix <code>StatementCache::Substitute</code> with serialized type.</p>
<p><em>ywenc</em></p>
</li>
<li>
<p>Fix <code>:db_runtime</code> on notification payload when application
have multiple databases.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/blob/v7.0.7/activemodel/CHANGELOG.md">activemodel's
changelog</a>.</em></p>
<blockquote>
<h2>Rails 7.0.7 (August 09, 2023)</h2>
<ul>
<li>
<p>Error.full_message now strips &quot;:base&quot; from the message.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Add a load hook for <code>ActiveModel::Model</code> (named
<code>active_model</code>) to match the load hook for
<code>ActiveRecord::Base</code> and allow for overriding aspects of the
<code>ActiveModel::Model</code> class.</p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/522c86f35ccc80453ed9fb6ca8b394db321f9a69"><code>522c86f</code></a>
Preparing for 7.0.7 release</li>
<li><a
href="https://github.com/rails/rails/commit/64ea100832b0a40eb8776e93cae6dd813fb5613d"><code>64ea100</code></a>
Make sure nested base errors are translatable</li>
<li><a
href="https://github.com/rails/rails/commit/d52ac5c1f81e5eadcc942baf987374964e476e62"><code>d52ac5c</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/48871">#48871</a>
from zzak/fix-am-error-full_message</li>
<li><a
href="https://github.com/rails/rails/commit/704cac833ae9c663d85d674f2b7764b7dd2ab62d"><code>704cac8</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/48730">#48730</a>
from Shopify/eagerly-cast-serialized-query-attributes</li>
<li><a
href="https://github.com/rails/rails/commit/41a998e762cc96a912065d6dccff236143024b56"><code>41a998e</code></a>
Fix issue with attr_protected where malformed input could
circumvent</li>
<li>See full diff in <a
href="https://github.com/rails/rails/compare/v7.0.6...v7.0.7">compare
view</a></li>
</ul>
</details>
<br />

Updates `actionpack` from 7.0.6 to 7.0.7
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">actionpack's
releases</a>.</em></p>
<blockquote>
<h2>7.0.7</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>Cache::NullStore</code> with local caching for repeated
reads.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix <code>to_s</code> with no arguments not respecting custom
<code>:default</code> formats</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising
<code>NoMethodError: undefined method `end_with?' for
nil:NilClass</code>.</p>
<p><em>James Robinson</em></p>
</li>
<li>
<p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p>
<p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan
Hefner</em></p>
</li>
<li>
<p>Improve error message when EventedFileUpdateChecker is used without a
compatible version of the Listen gem</p>
<p><em>Hartley McGuire</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Error.full_message now strips &quot;:base&quot; from the message.</p>
<p><em>zzak</em></p>
</li>
<li>
<p>Add a load hook for <code>ActiveModel::Model</code> (named
<code>active_model</code>) to match the load hook for
<code>ActiveRecord::Base</code> and allow for overriding aspects of the
<code>ActiveModel::Model</code> class.</p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Restores functionality to the missing method when using enums and
fixes.</p>
<p><em>paulreece</em></p>
</li>
<li>
<p>Fix <code>StatementCache::Substitute</code> with serialized type.</p>
<p><em>ywenc</em></p>
</li>
<li>
<p>Fix <code>:db_runtime</code> on notification payload when application
have multiple databases.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/blob/v7.0.7/actionpack/CHANGELOG.md">actionpack's
changelog</a>.</em></p>
<blockquote>
<h2>Rails 7.0.7 (August 09, 2023)</h2>
<ul>
<li>No changes.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/522c86f35ccc80453ed9fb6ca8b394db321f9a69"><code>522c86f</code></a>
Preparing for 7.0.7 release</li>
<li><a
href="https://github.com/rails/rails/commit/c05a88d1c996d910c9c50a9b151b65e722a42a7d"><code>c05a88d</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/45116">#45116</a>
from ghiculescu/helper_method_backtrace</li>
<li>See full diff in <a
href="https://github.com/rails/rails/compare/v7.0.6...v7.0.7">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>