Bump activestorage from 7.1.3.4 to 7.1.4 in /spec/tester_mongo (#857)
Bumps [activestorage](https://github.com/rails/rails) from 7.1.3.4 to
7.1.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activestorage's
releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for
<code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by
default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/6f57590388ca38ed2b83bc1207a8be13a9ba2aef"><code>6f57590</code></a>
Preparing for 7.1.4 release</li>
<li><a
href="https://github.com/rails/rails/commit/63fe89d0f5ee949f316c50c0bd1b3494ae5ec397"><code>63fe89d</code></a>
Sync changelog</li>
<li><a
href="https://github.com/rails/rails/commit/eedbe69470962e2ac1fb91913b8104a0c873d17a"><code>eedbe69</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/6cd12dee2213f42f4d7a8e37c1d3359592be0f64"><code>6cd12de</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/51907">#51907</a>
from higher-pixels/no-doc-preview-image-needed</li>
<li><a
href="https://github.com/rails/rails/commit/0dc6be257278d3d2bd7b853d0ab1038bec41f7de"><code>0dc6be2</code></a>
Merge branch 'rm-trix-7-1' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/ed84c0d8b0016fd8387d34453803e21c177bcb2b"><code>ed84c0d</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/8e2101f9b575e081f3a0a29424925481ef326ac1"><code>8e2101f</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/410b6da5427a35aa2ddf5146193e24fd8c31194c"><code>410b6da</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/50995">#50995</a>
from zzak/7-1/asto-configs</li>
<li><a
href="https://github.com/rails/rails/commit/6f729dd39f396c12cf15bd87695e0c3f463bd675"><code>6f729dd</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/51030">#51030</a>
from searls/queue-approach-to-preview-image-race-co...</li>
<li><a
href="https://github.com/rails/rails/commit/0c666263706c83c3f725ca09e105a960877910d2"><code>0c66626</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/50892">#50892</a>
from Takahashi-Seiji/main</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.1.3.4...v7.1.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activestorage&package-manager=bundler&previous-version=7.1.3.4&new-version=7.1.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>