Bump railties from 7.1.3.4 to 7.1.4 (#852)
Bumps [railties](https://github.com/rails/rails) from 7.1.3.4 to 7.1.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">railties's
releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for
<code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by
default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/6f57590388ca38ed2b83bc1207a8be13a9ba2aef"><code>6f57590</code></a>
Preparing for 7.1.4 release</li>
<li><a
href="https://github.com/rails/rails/commit/63fe89d0f5ee949f316c50c0bd1b3494ae5ec397"><code>63fe89d</code></a>
Sync changelog</li>
<li><a
href="https://github.com/rails/rails/commit/c53ec4b60980036b43528829d4b0b7457f759224"><code>c53ec4b</code></a>
Fix migration ordering for <code>bin/rails db:prepare</code> across
databases</li>
<li><a
href="https://github.com/rails/rails/commit/91102fa81943e7c6c6e0400f5ab699ee2d92de93"><code>91102fa</code></a>
Update puma.rb.tt</li>
<li><a
href="https://github.com/rails/rails/commit/e1af58ff7f67a51e4231bf5d10b402c4eeac26a6"><code>e1af58f</code></a>
fix puma.rb.tt</li>
<li><a
href="https://github.com/rails/rails/commit/7bd61c5e0b6ddfca1d7f9d4fd00f6450ca452e79"><code>7bd61c5</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52100">#52100</a>
from jdlubrano/fix-activerecord-configs-shadowing</li>
<li><a
href="https://github.com/rails/rails/commit/f6f9166c355c5535f4735449cc242e8c1cd19ee6"><code>f6f9166</code></a>
Fix running migrations on other databases when <code>database_tasks:
false</code> on pri...</li>
<li><a
href="https://github.com/rails/rails/commit/eedbe69470962e2ac1fb91913b8104a0c873d17a"><code>eedbe69</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/bb720db444190e57c8cc6ffc9fb6b0ff7a82bcf1"><code>bb720db</code></a>
Lower case the <code>link</code> header</li>
<li><a
href="https://github.com/rails/rails/commit/49c7f6561d7a8d6d112bfaebd1a67001d67ffc5d"><code>49c7f65</code></a>
Require <code>action_view/helpers</code> instead of
<code>rails-html-sanitizer</code></li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.1.3.4...v7.1.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=railties&package-manager=bundler&previous-version=7.1.3.4&new-version=7.1.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>