Bump actionmailer from 7.1.3.4 to 7.1.4 in /spec/tester_mongo (#861)
Bumps [actionmailer](https://github.com/rails/rails) from 7.1.3.4 to
7.1.4.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">actionmailer's
releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for
<code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by
default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/6f57590388ca38ed2b83bc1207a8be13a9ba2aef"><code>6f57590</code></a>
Preparing for 7.1.4 release</li>
<li><a
href="https://github.com/rails/rails/commit/eedbe69470962e2ac1fb91913b8104a0c873d17a"><code>eedbe69</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/0dc6be257278d3d2bd7b853d0ab1038bec41f7de"><code>0dc6be2</code></a>
Merge branch 'rm-trix-7-1' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/bb28ca8f0a7874bb07bdea38dad46184956e0855"><code>bb28ca8</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/51510">#51510</a>
from fatkodima/remove-ostruct</li>
<li><a
href="https://github.com/rails/rails/commit/ed84c0d8b0016fd8387d34453803e21c177bcb2b"><code>ed84c0d</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/8e2101f9b575e081f3a0a29424925481ef326ac1"><code>8e2101f</code></a>
Merge branch '7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/0707d731b8bfadd1c672e73c0894bc7f8c1c96f7"><code>0707d73</code></a>
Register autoload for ActiveJob::Arguments</li>
<li><a
href="https://github.com/rails/rails/commit/63763f25ebb9f7840b75eca067ec3c7f360bd301"><code>63763f2</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/50789">#50789</a>
from p8/docs/relative-includes (<a
href="https://redirect.github.com/rails/rails/issues/50863">#50863</a>)</li>
<li>See full diff in <a
href="https://github.com/rails/rails/compare/v7.1.3.4...v7.1.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=actionmailer&package-manager=bundler&previous-version=7.1.3.4&new-version=7.1.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>