Bump rspec-rails and rails in /spec/tester_mongo_rails_6 (#877)
Bumps [rspec-rails](https://github.com/rspec/rspec-rails) and
[rails](https://github.com/rails/rails). These dependencies needed to be
updated together.
Updates `rspec-rails` from 6.1.5 to 7.0.1
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rspec/rspec-rails/blob/main/Changelog.md">rspec-rails's
changelog</a>.</em></p>
<blockquote>
<h3>7.0.1 / 2024-09-03</h3>
<p><a
href="https://github.com/rspec/rspec-rails/compare/v7.0.0...v7.0.1">Full
Changelog</a></p>
<p>Bug Fixes:</p>
<ul>
<li>Remove mutation of Rails constant in favour of public api. (Petrik
de Heus, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2789">#2789</a>)</li>
<li>Cleanup Rails scaffold for unsupported versions. (Matt Jankowski, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2790">#2790</a>)</li>
<li>Remove deprecated scaffold that was unintentionally included in
7.0.0
(Jon Rowe, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2791">#2791</a>)</li>
</ul>
<h3>7.0.0 / 2024-09-02</h3>
<p><a
href="https://github.com/rspec/rspec-rails/compare/v6.1.5...v7.0.0">Full
Changelog</a></p>
<p>Enhancements:</p>
<ul>
<li>Change default driver for system specs on Rails 7.2 to match its
default.
(Steve Polito, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2746">#2746</a>)</li>
<li>Verify ActiveJob arguments by comparing to the method signature.
(Oli Peate, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2745">#2745</a>)</li>
<li>Add suggestion to rails_helper.rb to skip when not in test most.
(Glauco Custódio, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2751">#2751</a>)</li>
<li>Add <code>at_priority</code> qualifier to
<code>have_enqueued_job</code> set of matchers. (mbajur, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2759">#2759</a>)</li>
<li>Add spec directories to <code>rails stats</code> on Rails main /
8.0.0. (Petrik de Heus, <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2781">#2781</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rspec/rspec-rails/commit/a1e2f6ced874e29c8585977e2fcde499c957cb1b"><code>a1e2f6c</code></a>
v7.0.1</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/b9d5676b5ac462e1dc26b79551bb40b6cfbd8f01"><code>b9d5676</code></a>
Merge pull request <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2791">#2791</a>
from rspec/cleanup-rails-6-1</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/bbf16f9f4c966c5c0e833e0d794e80d8ceda89b2"><code>bbf16f9</code></a>
Changelog for <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2789">#2789</a>
and <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2790">#2790</a></li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/0beb36ed80df55bd0a68222ee854fe40a5c38d26"><code>0beb36e</code></a>
Merge pull request <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2790">#2790</a>
from mjankowski/cell-selector-rails-version</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/a124bb71d57004ec270347f48b8e483e51c7841c"><code>a124bb7</code></a>
Merge pull request <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2789">#2789</a>
from p8/code-statistics-test-dirs</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/1bb407e749e41e4fd7de898771833284476e0b03"><code>1bb407e</code></a>
v7.0.0</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/8c870d69a63aea9cb9c3a6ad5208f3a9050f666a"><code>8c870d6</code></a>
Merge pull request <a
href="https://redirect.github.com/rspec/rspec-rails/issues/2788">#2788</a>
from rspec/7-0-prep</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/a5d063516049444257dad1bef2ef3e2a5be731f2"><code>a5d0635</code></a>
Update rails link</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/3b36479346daa334d2d5d89fbbdaf434af1a60d6"><code>3b36479</code></a>
Drop 6.1 related code</li>
<li><a
href="https://github.com/rspec/rspec-rails/commit/4dd952191c0069f4920e370f32abacf2555f3c73"><code>4dd9521</code></a>
Rewrite upgrade notes</li>
<li>Additional commits viewable in <a
href="https://github.com/rspec/rspec-rails/compare/v6.1.5...v7.0.1">compare
view</a></li>
</ul>
</details>
<br />

Updates `rails` from 6.1.7.8 to 7.1.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">rails's
releases</a>.</em></p>
<blockquote>
<h2>7.1.4</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Improve compatibility for
<code>ActiveSupport::BroadcastLogger</code>.</p>
<p><em>Máximo Mussini</em></p>
</li>
<li>
<p>Pass options along to write_entry in handle_expired_entry method.</p>
<p><em>Graham Cooper</em></p>
</li>
<li>
<p>Fix Active Support configurations deprecations.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix teardown callbacks.</p>
<p><em>Tristan Starck</em></p>
</li>
<li>
<p><code>BacktraceCleaner</code> silence core internal methods by
default.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix <code>delegate_missing_to allow_nil: true</code> when called with
implict self</p>
<pre lang="ruby"><code>class Person
  delegate_missing_to :address, allow_nil: true
<p>def address<br />
nil<br />
end</p>
<p>def berliner?<br />
city == &quot;Berlin&quot;<br />
end<br />
end</p>
<p>Person.new.city # =&gt; nil<br />
Person.new.berliner? # undefined local variable or method `city' for an
instance of Person (NameError)<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Work around a Ruby bug that can cause a VM crash.</p>
<p>This would happen if using <code>TaggerLogger</code> with a Proc
formatter on which you called <code>object_id</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/6f57590388ca38ed2b83bc1207a8be13a9ba2aef"><code>6f57590</code></a>
Preparing for 7.1.4 release</li>
<li><a
href="https://github.com/rails/rails/commit/63fe89d0f5ee949f316c50c0bd1b3494ae5ec397"><code>63fe89d</code></a>
Sync changelog</li>
<li><a
href="https://github.com/rails/rails/commit/8d629558ee2b0d908d5d8a3427fb4439762f1b18"><code>8d62955</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52585">#52585</a>
from Shopify/fix-docs-linting</li>
<li><a
href="https://github.com/rails/rails/commit/6036b6511e2310cda062beb8a14b9e3f69fc2ba6"><code>6036b65</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52138">#52138</a>
from skipkayhil/hm-rack-input-is-optional</li>
<li><a
href="https://github.com/rails/rails/commit/578eb9a918a7a63554353575f909f9a61ea0a67f"><code>578eb9a</code></a>
Move the rewind code closer to the reason why we need to rewind</li>
<li><a
href="https://github.com/rails/rails/commit/fef23ff27fd7d84e53ec999c7b98b5dbf8aa6f0f"><code>fef23ff</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52281">#52281</a>
from jagthedrummer/jeremy/action-text-content-trix-fix</li>
<li><a
href="https://github.com/rails/rails/commit/128b5b03babbdd0dd0d0e2fb224f956aef92ad2e"><code>128b5b0</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52631">#52631</a>
from zenspider/zenspider/minitest-cleanup</li>
<li><a
href="https://github.com/rails/rails/commit/62abd092f8e659e0bf116fa8649447bbf818754e"><code>62abd09</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52619">#52619</a>
from fatkodima/eager-load-nil-associations</li>
<li><a
href="https://github.com/rails/rails/commit/dbc560d7b1f4c7463b0140fcacd2be5f8e10be56"><code>dbc560d</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52609">#52609</a>
from rails/rm-minitest</li>
<li><a
href="https://github.com/rails/rails/commit/6a14308792551afd01b2375ad7b79621081f7d19"><code>6a14308</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52591">#52591</a>
from fatkodima/fix-create_table-with-auto_increment</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v6.1.7.8...v7.1.4">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>