Bump activesupport from 7.1.4.2 to 7.1.5 in /spec/tester_mongo (#995)
Bumps [activesupport](https://github.com/rails/rails) from 7.1.4.2 to
7.1.5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activesupport's
releases</a>.</em></p>
<blockquote>
<h2>7.1.5</h2>
<h2>Active Support</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Fix regression in <code>alias_attribute</code> to work with user
defined methods.</p>
<p><code>alias_attribute</code> would wrongly assume the attribute
accessor was generated by Active Model.</p>
<pre lang="ruby"><code>class Person
  include ActiveModel::AttributeMethods
<p>define_attribute_methods :name<br />
attr_accessor :name</p>
<p>alias_attribute :full_name, :name<br />
end</p>
<p>person.full_name # =&gt; NoMethodError: undefined method `attribute'
for an instance of Person<br />
</code></pre></p>
<p><em>Jean Boussier</em></p>
</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix marshalling of unsaved associated records in 7.1 format.</p>
<p>The 7.1 format would only marshal associated records if the
association was loaded.
But associations that would only contain unsaved records would be
skipped.</p>
<p><em>Jean Boussier</em></p>
</li>
<li>
<p>Fix an issue where <code>.left_outer_joins</code> used with multiple
associations that have
the same child association but different parents does not join all
parents.</p>
<p>Previously, using <code>.left_outer_joins</code> with the same child
association would only join one of the parents.</p>
<p>Now it will correctly join both parents.</p>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/41498">#41498</a>.</p>
<p><em>Garrett Blehm</em></p>
</li>
<li>
<p>Ensure <code>ActiveRecord::Encryption.config</code> is always ready
before access.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/625ec92428e2c2575d5f6345d6f7bdec3865a617"><code>625ec92</code></a>
Preparing for 7.1.5 release</li>
<li><a
href="https://github.com/rails/rails/commit/252723d69757ef16bda32b03199034a2c82e366e"><code>252723d</code></a>
Avoid redefining IpAddr#as_json if it already exist</li>
<li><a
href="https://github.com/rails/rails/commit/3ddbd08123d48f58cf50f579d50b33a9ad23a505"><code>3ddbd08</code></a>
Merge remote-tracking branch 'origin/7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/d3ceb6cdabf0835c7a02fcdf9421f279e7abcef5"><code>d3ceb6c</code></a>
Merge remote-tracking branch 'origin/7-1-sec' into 7-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/ed1cdb4c01abac5296c75405123e1931ac948905"><code>ed1cdb4</code></a>
Small Ruby 3.4 fixes in the test suite</li>
<li><a
href="https://github.com/rails/rails/commit/b31fcef74c1870aaec3bd36bf942c6b63f7c50bc"><code>b31fcef</code></a>
Backport some more Ruby 3.4 compatibily fixes</li>
<li><a
href="https://github.com/rails/rails/commit/64734753d52414b2074eec3d86380baff0376df9"><code>6473475</code></a>
Ruby 3.4: add extracted standard gems to activesupport.gemspec</li>
<li><a
href="https://github.com/rails/rails/commit/cce9ecbd0b19f4e834f3ad41549240356a775dc0"><code>cce9ecb</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/53202">#53202</a>
from byroot/ruby-3.4-hash-inspect</li>
<li><a
href="https://github.com/rails/rails/commit/96c224aa711ec309489d4ce94f55e00d6861d851"><code>96c224a</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52868">#52868</a>
from soulcutter/broadcast-logger-delegation</li>
<li><a
href="https://github.com/rails/rails/commit/cf17539d1409d0d55c6c0a457f9f65e9c0e8c5f9"><code>cf17539</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/52853">#52853</a>
from zzak/as-deprecation-reporting-constants-nodoc</li>
<li>See full diff in <a
href="https://github.com/rails/rails/compare/v7.1.4.2...v7.1.5">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activesupport&package-manager=bundler&previous-version=7.1.4.2&new-version=7.1.5)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>